### ISSUE TITLE
Where should I find the DBP15K module and preprocessor.py file? 

### ISSUE THREAD

**Issue by yanxiao0201** [syxu828/Crosslingula-KG-Matching#15]
Hi we are a group at LinkedIn and would like to repeat this work. This file is missing. Could you help us find the correct file ?

**Comment by syxu828** [comment]
Hi It is in https://drive.google.com/open?id=1dYJtj1_J4nYJdrDY95ucGLCuZXDXI7PL

**Comment by 3waterya** [comment]
The link is broken. Could you share it again?
