### ISSUE TITLE
preprocessor.py missing?

### ISSUE THREAD

**Issue by DexterZeng** [syxu828/Crosslingula-KG-Matching#2]
Hi, thx for sharing the code! It seems that the preprocessor.py file is missing?

Many thanks,
Weixin.

**Comment by syxu828** [comment]
Hi, that code is under the DBP15K directory that we provide for downloading.
You can find that url address in READ.ME.

**Comment by nxznm** [comment]
Hi @DexterZeng, do you have a copy of the files from https://drive.google.com/open?id=1dYJtj1_J4nYJdrDY95ucGLCuZXDXI7PL (I found this link was broken)?
