### ISSUE TITLE
关于id_features

### ISSUE THREAD

**Issue by MaoXinn** [syxu828/Crosslingula-KG-Matching#5]
我检查了preprocess中的代码，发现实体特征并非由论文中所描述的那样, 由跨语言词向量生成
而是通过id_features_1和id_features_2文件中的英文，查找同一英文词向量生成
据我观察id_features_1 和 id_features_2是通过机器翻译手段得到的，而论文中完全没有相关表述
这个代码实现与论文中差异过大，我是否在哪里理解错误？

**Comment by syxu828** [comment]
这两种方法都是用同一个空间的embedding来表示跨语言的单词，对模型的本身性能没有什么影响。

**Comment by kilinchange** [comment]
请问可以给出跨语言词向量表示的实体特征吗？
