### ISSUE TITLE
What's the reason for successive transpose?

### ISSUE THREAD

**Issue by acharkq** [syxu828/Crosslingula-KG-Matching#6]
https://github.com/syxu828/Crosslingula-KG-Matching/blob/56710f8131ae072f00de97eb737315e4ac9510f2/neigh_samplers.py#L16

As mentioned in the tile, does the transpose do something inside the tensor? Or is it just a joke or typo?

**Comment by syxu828** [comment]
It should be a typo. This transpose operation does not affect the results. We will fix this.
